### ISSUE TITLE
Restrict plugin to only macOS

### ISSUE THREAD

**Issue by gilday** [gilday/dark-mode-sync-plugin#1]
This plugin only works on macOS, so it would be nice to restrict its installation to only IDEs running on macOS.

This is not currently possible. See https://youtrack.jetbrains.com/issue/IJSDK-578

**Comment by YannCebron** [comment]
please also see `com.intellij.openapi.util.SystemInfo` for runtime check of OS/version

**Comment by gilday** [comment]
`com.intellij.openapi.util.SystemInfo` is awesome - I'm about to have a code deletion party.

**Comment by kannicht** [comment]
I think this issue can be closed as the plugin supports macOS with the new method and (hopefully) soon supports Windows 10 using the same method.
