### ISSUE TITLE
Source Code Annotations do not switch themes

### ISSUE THREAD

**Issue by madrob** [gilday/dark-mode-sync-plugin#11]
When the OS switches between light/dark modes, most of the UI updates but if the Annotations are open (showing e.g. git blame) that pane does not change colors.

Workaround: Closing and reopening the pane fixes this.

**Comment by kannicht** [comment]
Just to make sure:

Did you try a manual theme switch without the plugin? How is the behavior in that case?

**Comment by madrob** [comment]
Just tried the manual theme switch, looks like this is actually an IntelliJ bug. Thanks!

**Comment by madrob** [comment]
https://youtrack.jetbrains.com/issue/IDEA-233913
