### ISSUE TITLE
not supported by IDEA 2020.2

### ISSUE THREAD

**Issue by BorzdeG** [gilday/dark-mode-sync-plugin#20]

**Comment by jirkadev** [comment]
thanks for releasing a fix:)

**Comment by stevesfdc** [comment]
> thanks for releasing a fix:)

Is there a new published release of this plug-in scheduled with the above commit?

**Comment by gilday** [comment]
I totally missed these issues. I'm not sure how, but at some point I unwatched my own repo 🤦 . This is biting me too now that the new IntelliJ has been released. Let me get these changes merged and released

**Comment by gilday** [comment]
Submitted to JetBrains for review. Should be on the marketplace in a few days

**Comment by gilday** [comment]
Update is live on the Marketplace sooner than expected

**Comment by huehnerlady** [comment]
Great Service many thanks ❤️
