### ISSUE TITLE
[Bug] Version 1.2.6 incompatible with PyCharm/Intellij 2020.3

### ISSUE THREAD

**Issue by stevesfdc** [gilday/dark-mode-sync-plugin#27]
The latest version of JetBrains IDEs (2020.3) is no longer compatible with Dark Mode Sync: this has cropped up before.  Is there an easy way to update this for the latest versions of the IDEs?

Thanks!

-Steve

**Comment by gilday** [comment]
JetBrains 2020.3 has this functionality built-in, so this plug-in is no longer needed for the newest versions of JetBrains IDEs.
