### ISSUE TITLE
Incompatible with latest release of Goland 

### ISSUE THREAD

**Issue by simar7** [gilday/dark-mode-sync-plugin#28]
Hi there!

Thank you for this plugin, it has been working great so far. 

Recently, it has stopped working with Goland (IntelliJ based Golang IDE)

Goland Version: GoLand 2020.3
Build #GO-203.5981.98, built on November 24, 2020

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1254783/102290050-09f6a200-3ef5-11eb-96be-78858defcf7c.png">

Would it be possible to add support for 2020.3+ versions? I assume it would be similar to this PR? https://github.com/gilday/dark-mode-sync-plugin/pull/21

**Comment by simar7** [comment]
Sorry I filed this too soon - I realize that now it's officially supported within 2020.3 IntelliJ IDEs as this has merged https://youtrack.jetbrains.com/issue/IDEA-203554

Thanks again for this plugin, it served well until now!

**Comment by gilday** [comment]
That's right, this functionality is now baked in!

Duplicates #26
