### ISSUE TITLE
Follow "dark window headers" IDE setting

### ISSUE THREAD

**Issue by fehbari** [gilday/dark-mode-sync-plugin#3]
Currently the plugin seems the ignore the "Use dark window headers" setting.

<img width="415" alt="Captura de Tela 2019-11-19 às 04 02 01" src="https://user-images.githubusercontent.com/3378355/69123916-5c128d00-0a81-11ea-9583-8026d62d45fb.png">

As you can see in the screenshot, new opened windows reflect the desired setting. But previously opened windows keep whatever was set when the IDE started, leading to either a) Light theme with dark title bar; or B) Dark theme with light title bar.

It takes either restarting the IDE or closing the window for the title bar to appear correctly.

I believe the plugin could be missing reading and/or updating registry setting `ide.mac.allowDarkWindowDecorations`, but I can't be sure (not familiar with the plugin SDK).

To reproduce the issue just enable the setting and try switching Dark Mode back and forth.

**Comment by kannicht** [comment]
This is obsolete as Jetbrains removed (at least in IntelliJ) the checkbox for dark headers as this is now integrated into the themes themselves.

**Comment by fehbari** [comment]
@kannicht Not sure I follow, the setting is still there in IntelliJ 2019.2.4 (latest stable). Was it removed in previews? Are you experiencing correct header behavior on macOS with this plugin?

**Comment by fehbari** [comment]
I can confirm the setting is gone in 2019.3, but unfortunately the plugin itself is now flagged as incompatible and doesn't work.

**Comment by kannicht** [comment]
@fehbari I just opened a pull request on that matter. #5

**Comment by gilday** [comment]
Was the "Use dark window headers" setting removed in 2019.3?

**Comment by fehbari** [comment]
> Was the "Use dark window headers" setting removed in 2019.3?

It was. I can confirm after running the updated plugin locally, the header follows the theme properly (i.e. Darcula switches to a dark header automatically, Light to a light header), so it’s no longer an issue.

**Comment by gilday** [comment]
Thanks. I guess that means it's still an issue for users who haven't upgraded to 2019.3 yet, but good to know there is a workaround once 2019.3 support is released.

**Comment by fehbari** [comment]
> I guess that means it's still an issue for users who haven't upgraded to 2019.3 yet

Yes, that’s true! Please feel free to reopen this if you feel getting it fixed for older versions is worth addressing
