### ISSUE TITLE
Error on MacOS after update to Rider 2021.1.3

### ISSUE THREAD

**Issue by BrennonTWilliams** [gilday/dark-mode-sync-plugin#30]
After update this error is thrown on startup:

```Plugin error: Plugin 'Dark Mode Sync' (version '1.2.6') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is RD-211.7442.29```

Will there be a release to resolve this?

Thank you, love this tool!

**Comment by gilday** [comment]
This functionality is now [built into Rider](https://www.jetbrains.com/help/rider/Settings_Appearance.html) (and the JetBrains platform more generally). You no longer need this plugin to keep your theme synced with your OS! That is why I am not releasing a new version of the plugin.

Duplicates #26
